In [24]:
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [25]:
import requests

def download(url, filename):
    r = requests.get(url)
    if r.status_code == 200:
        with open(filename, "wb") as f:
            f.write(r.content)
        print("File downloaded successfully.")
    else:
        print("File not downloaded. Status Code:", r.status_code)

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/module_5_auto.csv"

filename = "module_5_auto.csv"

download(url, filename)

File downloaded successfully.


In [26]:
df = pd.read_csv('module_5_auto.csv',header=0)

In [27]:
df.head(20)

,Unnamed: 0.1,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0,0,3,122,alfa-romero,std,two,convertible,rwd,front,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,1,1,3,122,alfa-romero,std,two,convertible,rwd,front,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,3,3,2,164,audi,std,four,sedan,fwd,front,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,4,4,2,164,audi,std,four,sedan,4wd,front,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
5,5,5,2,122,audi,std,two,sedan,fwd,front,...,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1
6,6,6,1,158,audi,std,four,sedan,fwd,front,...,8.5,110.0,5500.0,19,25,17710.0,12.368421,Medium,0,1
7,7,7,1,122,audi,std,four,wagon,fwd,front,...,8.5,110.0,5500.0,19,25,18920.0,12.368421,Medium,0,1
8,8,8,1,158,audi,turbo,four,sedan,fwd,front,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1
9,9,9,2,192,bmw,std,two,sedan,rwd,front,...,8.8,101.0,5800.0,23,29,16430.0,10.217391,Low,0,1


In [28]:
df = df._get_numeric_data()
df

,Unnamed: 0.1,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,0,0,3,122,88.6,0.811148,0.890278,48.8,2548,130,...,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,0,1
1,1,1,3,122,88.6,0.811148,0.890278,48.8,2548,130,...,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,0,1
2,2,2,1,122,94.5,0.822681,0.909722,52.4,2823,152,...,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,0,1
3,3,3,2,164,99.8,0.848630,0.919444,54.3,2337,109,...,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,0,1
4,4,4,2,164,99.4,0.848630,0.922222,54.3,2824,136,...,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196,196,-1,95,109.1,0.907256,0.956944,55.5,2952,141,...,3.15,9.5,114.0,5400.0,23,28,16845.0,10.217391,0,1
197,197,197,-1,95,109.1,0.907256,0.955556,55.5,3049,141,...,3.15,8.7,160.0,5300.0,19,25,19045.0,12.368421,0,1
198,198,198,-1,95,109.1,0.907256,0.956944,55.5,3012,173,...,2.87,8.8,134.0,5500.0,18,23,21485.0,13.055556,0,1
199,199,199,-1,95,109.1,0.907256,0.956944,55.5,3217,145,...,3.40,23.0,106.0,4800.0,26,27,22470.0,9.038462,1,0


In [29]:
df.head()

,Unnamed: 0.1,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,0,0,3,122,88.6,0.811148,0.890278,48.8,2548,130,...,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,0,1
1,1,1,3,122,88.6,0.811148,0.890278,48.8,2548,130,...,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,0,1
2,2,2,1,122,94.5,0.822681,0.909722,52.4,2823,152,...,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,0,1
3,3,3,2,164,99.8,0.848630,0.919444,54.3,2337,109,...,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,0,1
4,4,4,2,164,99.4,0.848630,0.922222,54.3,2824,136,...,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,0,1


In [30]:
#lets remove column Unnamed: 0.1	Unnamed: 0
df.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1,inplace = True)
df.head()



,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,3,122,88.6,0.811148,0.890278,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,0,1
1,3,122,88.6,0.811148,0.890278,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,0,1
2,1,122,94.5,0.822681,0.909722,52.4,2823,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,0,1
3,2,164,99.8,0.848630,0.919444,54.3,2337,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,0,1
4,2,164,99.4,0.848630,0.922222,54.3,2824,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,0,1


**function for plotting**

In [34]:
def DistributionPlot(RedFunction,BlueFunction,RedName,BlueName,Title):
    plt.Figure(figsize=(12,4))
    ax1 = sns.kdeplot(RedFunction,color = 'r',label = 'RedName')
    ax2 = sns.kdeplot(BlueFunction,color = 'b',label = 'BlueName')

    plt.title(Title)
    plt.xlabel('Price (in dollars)')
    plt.ylabel('Proportion of Cars')
    plt.show()
    

In [37]:
def pollyplot(xtrain,xtest,y_train,y_test,lr,poly_transform):

    plt.Figure(figsize=(12,5))

    xmax = max([xtrain.values.max(),xtest.values.max()])
    xmin = max([xtrain.values.min(),xtest.values.min()])
    x = np.arrange(xmax,xmin,0.1)

    plt.plot(xtrain,y_train,'ro',label = 'Training_data')
    plt.plot(xtest,y_test,'go',label = 'Test_data')
    plt.plot(x,lr.predict(poly_transform.fit_transform(x.reshape(-1,1))),label = 'Predicted_function')
    plt.ylim([-10000,60000])
    plt.ylabel('Price')
    plt.legend()
    plt.show()

**Part 1: Training and Testing**

In [41]:
y_data = df['price']

In [42]:
x_data = df.drop('price',axis = 1)

In [43]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.10,random_state = 1)

print("number of test samples :", x_test.shape[0])
print("number of training samples:",x_train.shape[0])

number of test samples : 21
number of training samples: 180


In [47]:
from sklearn.model_selection import train_test_split

x_train1,x_test1,y_train1,y_test1 = train_test_split(x_data,y_data,test_size=0.4,random_state=0)

print("number of test samples :", x_test1.shape[0])
print("number of training samples:",x_train1.shape[0])




number of test samples : 81
number of training samples: 120


**Let's import LinearRegression from the module linear_model.**

In [48]:
from sklearn.linear_model import LinearRegression

lrm = LinearRegression()
#We fit the model using the feature "horsepower":
lrm.fit(x_train[['horsepower']],y_train)
#Let's calculate the R^2 on the test data:
lrm.score(x_test[['horsepower']],y_test)


0.3635875575078824

In [49]:
lrm.score(x_train[['horsepower']],y_train)

0.6619724197515103

**Find the R^2 on the test data using 40% of the dataset for testing.**

In [51]:
x_train1,x_test1,y_train1,y_test1 = train_test_split(x_data,y_data,test_size=0.4,random_state=0)
lrm.fit(x_test1[['horsepower']],y_test1)

LinearRegression()

In [53]:
lrm.score(x_train1[['horsepower']],y_train1)

0.4850746538215115

**Cross-Validation Score**

In [62]:
from sklearn.model_selection import cross_val_score
#We input the object, the feature ("horsepower"), and the target data (y_data). The parameter 'cv' determines the number of folds. In this case, it is 4.
Rcross = cross_val_score(lrm,x_data[['horsepower']],y_data,cv= 4)
Rcross

array([0.7746232 , 0.51716687, 0.74785353, 0.04839605])

In [63]:
print("mean of the folds are:",Rcross.mean(),"Standard deviation of folds are:",Rcross.std())

mean of the folds are: 0.5220099150421194 Standard deviation of folds are: 0.2911839444756025


In [65]:
# We can use negative squared error as a score by setting the parameter 'scoring' metric to 'neg_mean_squared_error'.
-1 * cross_val_score(lrm,x_data[['horsepower']], y_data,cv=4,scoring='neg_mean_squared_error')

array([20254142.84026704, 43745493.26505169, 12539630.34014931,
       17561927.72247589])

In [67]:
from sklearn.model_selection import cross_val_predict

yhat = cross_val_predict(lrm,x_data[['horsepower']],y_data,cv = 4)
yhat

array([14141.63807508, 14141.63807508, 20814.29423473, 12745.03562306,
       14762.35027598, 13986.46002486, 13986.46002486, 13986.46002486,
       18641.80153159, 12589.85757284, 12589.85757284, 15693.41857732,
       15693.41857732, 15693.41857732, 25159.27964101, 25159.27964101,
       25159.27964101,  4365.42091095,  7779.33801589,  7779.33801589,
        7468.98191544,  7468.98191544, 12745.03562306,  7468.98191544,
        7468.98191544,  7468.98191544, 12745.03562306, 10572.54291992,
       19417.69178271,  5917.2014132 ,  8710.40631723,  6227.55751364,
        8710.40631723,  8710.40631723,  8710.40631723,  8710.40631723,
       10262.18681948, 10262.18681948, 10262.18681948, 10262.18681948,
       12589.85757284, 12434.67952262,  9020.76241768, 10882.89902037,
       24228.21133966, 24228.21133966, 37573.52365895,  7468.98191544,
        7468.98191544,  7468.98191544,  7468.98191544,  7191.77534249,
       12625.21956696, 12625.21956696, 12625.21956696, 18223.31361641,
      

*******Part 2: Overfitting, Underfitting and Model Selection*******

In [68]:
#overfitting
from sklearn.preprocessing import PolynomialFeatures

x_train2,x_test2,y_train2,y_test2 = train_test_split(x_data,y_data,test_size=0.45,random_state=1)

pr = PolynomialFeatures(degree=5)
x_train_pr = pr.fit_transform(x_train[['horsepower']])
x_test_pr = pr.fit_transform(x_test[['horsepower']])
pr

PolynomialFeatures(degree=5)